### PR TITLE
Globalconfig.inc.php was disabled, and core module added to predefined allowed _modules

### PR DESCRIPTION
**Pull request by pvdvendjc**
The fine function of generating multi-instance configs based on the config of the servermanager had one issue in the globalconfig function.

Added array_merge of $config so Globalconfig vars will be set also.
Tested in my own environment and it works as expected. If no globalconfig is loaded then an empty $config will be set in advance of the merge.

Also added core module to required modules in the allowed_modules string.

### CODE REVIEW

**Comment by mschering** [comment]
The merge logic shouldn't be in the config.php file. The global config should just apply if the values are not present in the config.php. I thought your previous pull request already fixed that?

**Comment by pvdvendjc** [comment]
That function is overriden by the new Configfile. Because of line 198 in App.php (require($configFile)) the var $config gets a new value (because of $config = [....];) instead of the old logic where for each key was a $config['key'] = value; line.
Thus the output of the new configfile is quiet different. It can also be managed in the App.php but then has to be the logic there that you have to merge the configs instead of both a require statement.
The order of reading the configs can not be changed because the config-values should override the globalconfig-values if the same keys are used (e.g. allowed_modules).

**Comment by mschering** [comment]
Yes, but IMHO it should be fixed in App.php and not config.php. I will implement a fix for this.

**Comment by mschering** [comment]
I've added that now and fixed the merge with this commit:

https://github.com/Intermesh/groupoffice/commit/9b449aa8e08131b248362c3322acb56d796545a4

**Pull request closed without merging**
