### PR TITLE
Merge request to base 

### PR DESCRIPTION
**Pull request by pvdvendjc**
Solved these issues:
- Enabling / disabling of modules was not possible
- Output was not send to debug.log
- ClientName was not inserted into core_entity

### CODE REVIEW

**Comment by mschering** [comment]
I don't understand parts of this code:

1. Is the modules/djconsultancy folder intentional?
2. Why did you add the enabled check to isINstalled(). The idea is that disabled modules are treated as not installed. 
3. Output to debug.log was disabled intentionally. You should use the browser dev tools.

**Comment by mschering** [comment]
I've just pushed a commit that fixes some of these issues.

**Comment by pvdvendjc** [comment]
Hi Merijn,
1. These are my own modules that will not be in the main branch, to prevent uploading them I have added this to my .gitignore file
2. If you don't add this check then you cannot disable modules but only destroy them. By giving a default value all other checks work as intented. All modules disabled are still threathened as uninstalled.
3. Will that be easy if a customers has a problem and you has to support them?? The configparameter debug will stop filling that log isn´t it.

**Comment by pvdvendjc** [comment]
Hi Merijn,

The only change which stays with this merge is the disabling/enabling of modules in the ModuleManager.

Previous behaviour:
- Disable module works
- Enabling module tries the module to reinstall because te module has id null instead of the id in the core_module table.

Current behaviour:
- Disable module works
- Enabling module sets enabled flag to 1

**Pull request closed without merging**
