### PR TITLE
Several bug fixes

### PR DESCRIPTION
**Pull request by gtech99**

### CODE REVIEW

**Comment by mschering** [comment]
Thanks! But please break fixes up next time in several requests. I don't fully agree on all fixes :)

For example copy and delete instead of rename will have a very bad performance impact. Try moving a folder with a a few GB of files using that method. It will run into problems quickly while rename takes microseconds.
We fixed this in the newer lib go/core/FIle in a way that it falls back if rename fails. I'll port this over.

I'm afraid that the utf8ize function is also going to have great impact on performance. When did you ran into this problem? It should be fixed on the browser side I think.

**Comment by gtech99** [comment]
you're right about the performance issue of copy/delete vs rename. I think I did that because in a few places you were using rename to move across partitions and it's not working in that case.

utf8ize isn't supposed to run all the time, only when json_encode() fails. We had some cases of messages in Russian / Chinese where json_encode would fail and the message wouldn't render at all. This function was designed to sanitize that input only when json_encode() itself fails. In our experience this solved that problem.

Lastly, apologies for all the commits in one batch, we'll split them up next time - thank you for including them!

**Comment by mschering** [comment]
Just realized we already had a newer lib that handles this. 🙈 See https://github.com/Intermesh/groupoffice/blob/master/www/go/core/util/JSON.php

I'll use that function at this place.

**Comment by mschering** [comment]
Sorry, that just reported about it. I've implemented the cleanup there now.

**Pull request closed without merging**
