### PR TITLE
Bugfix/1080 oauth server compatibility kid nonce

### PR DESCRIPTION
**Pull request by michalcharvat**

### CODE REVIEW

**Comment by mschering** [comment]
I also made changes in master to fix it for bookstack. You fix seems to conflict with that:

https://github.com/Intermesh/groupoffice/commit/54533904547d966cc133de96e3ebe0e67e310bb7

**Comment by michalcharvat** [comment]
This PR is into 6.7.x branch so after that I have to create new PR or bring changes from 6.8.x to 6.7.x  which doe not make sense so from my point of view I have to prepare another PR with changes for main/6.8

**Comment by mschering** [comment]
Ok, please be aware that we merge everything from 6.7 to master so this will end up in master too. I will have to solve the conflicts.

**Comment by michalcharvat** [comment]
OK now it should be compatible with master. 

Btw it looks like master with php8.2 has problem with Lcobucci\JWT\Signer\Key\LocalFileReference;

**Comment by michalcharvat** [comment]
@mschering Shall I merge this request or do you see any other issue?

**Comment by mschering** [comment]
No looks good now. I've merged it. Thanks!

**Pull request merged**
