### PR TITLE
fix for #1067: Make Junk/Spam folder configurable

### LINKED ISSUE #1067: Enhancement: IMAP default folder list is incomplete
When you add an email account you can define _IMAP default folder_:
e.g.:
- Sent: INBOX.Sent
- Trash: INBOX.Trash
- Drafts: INBOX.Drafts

sadly there is one missing:
- Junk: INBOX.Junk

Kindly add configuration posibility for Junk/Spam folder.
It is annoying when GroupOffice is creating a _Spam_ folder while there is already a _Junk_ folder, that is being used by Thunderbird.
20231117_GroupOffice_IMAP_folder_defaults

### PR DESCRIPTION
**Pull request by computersalat**
Fix for #1067 
Not sure if I was able to catch all the needed things, because _Spam_ folder is _hardcoded_.

### CODE REVIEW

**Comment by mschering** [comment]
Thanks! Don't know why this was missing.

**Comment by computersalat** [comment]
@mschering 
Are you going to Cherry-Pick this to other branches, too ?

**Comment by mschering** [comment]
We'll merge it to master so it will be in future releases too.

**Comment by computersalat** [comment]
@mschering 
Just noticed that I forgot a CHANGELOG.md entry. Will you please add one ?
Thank you.

**Comment by mschering** [comment]
Done. Thank you!

**Pull request merged**
