### PR TITLE
Update FieldHelp.js

### PR DESCRIPTION
**Pull request by filerun**

### CODE REVIEW

**Comment by mschering** [comment]
Nice try, this was taken off a public extjs forum no license was present:

https://forum.sencha.com/forum/showthread.php?77984-Field-help-text-plugin

**Comment by michalcharvat** [comment]
@mschering Haha maybe you should ask Nigel (Animal) if he agree with copyright in file with his code :)) 2009 - ExtJS gold times

**Comment by mschering** [comment]
Haha, thanks. Yes that were good old days :)

**Comment by filerun** [comment]
:) my bad indeed on this. I'll reply to your e-mail though.

**Pull request closed without merging**
